version: '3'
services:
  rag:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./data/:/app/data
    ports:
      - 8000:8000
    env_file:
      - .env